[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.9.0-alpha.1"
image = "0.24.7"
indicatif = "0.17.8"
rayon = "1.10.0"
tobj = "4.0.2"
threadpool = "1.8.1"
